# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ashbourn', '0004_auto_20161204_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
