# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ashbourn', '0005_auto_20161204_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_data',
        ),
        migrations.AddField(
            model_name='activity',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='to_from',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
