# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ashbourn', '0006_auto_20161204_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='call_duration',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
